//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBTWebApplication.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IService3")]
    public interface IService3 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService3/GetEmployeeInfo", ReplyAction="http://tempuri.org/IService3/GetEmployeeInfoResponse")]
        string GetEmployeeInfo(string name, string address, string postcode, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService3/GetEmployeeInfo", ReplyAction="http://tempuri.org/IService3/GetEmployeeInfoResponse")]
        System.Threading.Tasks.Task<string> GetEmployeeInfoAsync(string name, string address, string postcode, string phone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService3Channel : BBTWebApplication.ServiceReference3.IService3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service3Client : System.ServiceModel.ClientBase<BBTWebApplication.ServiceReference3.IService3>, BBTWebApplication.ServiceReference3.IService3 {
        
        public Service3Client() {
        }
        
        public Service3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetEmployeeInfo(string name, string address, string postcode, string phone) {
            return base.Channel.GetEmployeeInfo(name, address, postcode, phone);
        }
        
        public System.Threading.Tasks.Task<string> GetEmployeeInfoAsync(string name, string address, string postcode, string phone) {
            return base.Channel.GetEmployeeInfoAsync(name, address, postcode, phone);
        }
    }
}
