//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBTWebApplication.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetCustomerInfo", ReplyAction="http://tempuri.org/IService2/GetCustomerInfoResponse")]
        string GetCustomerInfo(string name, string address, string postcode, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetCustomerInfo", ReplyAction="http://tempuri.org/IService2/GetCustomerInfoResponse")]
        System.Threading.Tasks.Task<string> GetCustomerInfoAsync(string name, string address, string postcode, string phone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : BBTWebApplication.ServiceReference2.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<BBTWebApplication.ServiceReference2.IService2>, BBTWebApplication.ServiceReference2.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCustomerInfo(string name, string address, string postcode, string phone) {
            return base.Channel.GetCustomerInfo(name, address, postcode, phone);
        }
        
        public System.Threading.Tasks.Task<string> GetCustomerInfoAsync(string name, string address, string postcode, string phone) {
            return base.Channel.GetCustomerInfoAsync(name, address, postcode, phone);
        }
    }
}
